### ISSUE TITLE
Working Reactflow, when i add a Panel it errors

### ISSUE THREAD

**Issue by techyogi** [xyflow/xyflow#4319]
### Describe the Bug

This works:
 <ReactFlow
            nodes={nodes}
            edges={edges}
            onNodesChange={onNodesChange}
            onEdgesChange={onEdgesChange}
            onConnect={onConnect}
            onInit={setRfInstance}
            proOptions={proOptions}
            fitView
            attributionPosition="top-right"
          >
            <Panel position="top-left">top-left</Panel>
</ReactFlow>

This does not work and reports error as below:
 <ReactFlow
            nodes={nodes}
            edges={edges}
            onNodesChange={onNodesChange}
            onEdgesChange={onEdgesChange}
            onConnect={onConnect}
            onInit={setRfInstance}
            proOptions={proOptions}
            fitView
            attributionPosition="top-right"
          >
            <Panel position="top-left">top-left</Panel>
</ReactFlow>

error from browser console:
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `AgentPage`.
    at AgentPage (http://localhost:3001/app_containers_Pages_AgentsPage_index_js.chunk.js:54:5)
    at injectIntl(AgentPage)
    at Suspense
    at Route (webpack://%5Bname%5D/./node_modules/react-router-dom/node_modules/react-router/cjs/react-router.js?:470:29)
    at Provider (webpack://%5Bname%5D/./node_modules/zustand/esm/context.js?:12:5)
    at ReactFlowProvider (webpack://%5Bname%5D/./node_modules/react-flow-renderer/dist/esm/index.js?:4167:23)
    at Switch (webpack://%5Bname%5D/./node_modules/react-router-dom/node_modules/react-router/cjs/react-router.js?:676:29)
    at div
    at Transition (http://localhost:3001/vendors-node_modules_firebase_auth_dist_auth_esm_js-node_modules_firebase_database_dist_index-e964e8.js:112033:30)
    at Fade (http://localhost:3001/vendors-node_modules_firebase_auth_dist_auth_esm_js-node_modules_firebase_database_dist_index-e964e8.js:49734:39)
    at section
    at main
    at LeftSidebarLayout (http://localhost:3001/main.js:12789:65)
    at injectIntl(LeftSidebarLayout)
    at div
    at Dashboard (http://localhost:3001/main.js:12206:66)
    at ConnectFunction (webpack://%5Bname%5D/./node_modules/react-redux/lib/components/connectAdvanced.js?:235:41)
    at Application (http://localhost:3001/main.js:11401:5)
    at Route (webpack://%5Bname%5D/./node_modules/react-router-dom/node_modules/react-router/cjs/react-router.js?:470:29)
    at Switch (webpack://%5Bname%5D/./node_modules/react-router-dom/node_modules/react-router/cjs/react-router.js?:676:29)
    at Router (webpack://%5Bname%5D/./node_modules/react-router-dom/node_modules/react-router/cjs/react-router.js?:99:30)
    at div
    at InnerThemeProvider (http://localhost:3001/vendors-node_modules_firebase_auth_dist_auth_esm_js-node_modules_firebase_database_dist_index-e964e8.js:76343:39)
    at ThemeProvider (http://localhost:3001/vendors-node_modules_firebase_auth_dist_auth_esm_js-node_modules_firebase_database_dist_index-e964e8.js:73571:5)
    at ThemeProvider (http://localhost:3001/vendors-node_modules_firebase_auth_dist_auth_esm_js-node_modules_firebase_database_dist_index-e964e8.js:76362:5)
    at ThemeWrapper (http://localhost:3001/main.js:11577:7)
    at ConnectFunction (webpack://%5Bname%5D/./node_modules/react-redux/lib/components/connectAdvanced.js?:235:41)
    at App (http://localhost:3001/main.js:11669:5)
    at Router (webpack://%5Bname%5D/./node_modules/react-router/cjs/react-router.js?:95:30)
    at ConnectedRouter (webpack://%5Bname%5D/./node_modules/connected-react18-router/lib/ConnectedRouter.js?:71:7)
    at ConnectedRouterWithContext (webpack://%5Bname%5D/./node_modules/connected-react18-router/lib/ConnectedRouter.js?:195:25)
    at ConnectFunction (webpack://%5Bname%5D/./node_modules/react-redux/lib/components/connectAdvanced.js?:235:41)
    at IntlProvider (webpack://%5Bname%5D/./node_modules/react-intl/src/components/provider.js?:88:47)
    at LanguageProvider (http://localhost:3001/main.js:11779:19)
    at ConnectFunction (webpack://%5Bname%5D/./node_modules/react-redux/lib/components/connectAdvanced.js?:235:41)
    at PersistGate (http://localhost:3001/vendors-node_modules_firebase_auth_dist_auth_esm_js-node_modules_firebase_database_dist_index-e964e8.js:114451:5)
    at Provider (webpack://%5Bname%5D/./node_modules/react-redux/lib/components/Provider.js?:21:20)

### Steps to Reproduce the Bug or Issue

uncomment the Panel and it will crash the app... All other plugins work.

### Expected behavior

Panel appears

### Platform

Latest Macos in any browser, but mostly brave

**Comment by bcakmakoglu** [comment]
Can you share some of your code with us?

**Comment by moklick** [comment]
please re-open with a codesandbox (https://new.reactflow.dev) or repo.
