### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'useRef')

### ISSUE THREAD

**Issue by AnandDhage** [xyflow/xyflow#4361]
### What platform were you using when you found the bug?

- React Flow : 11.11.3 
- Browser and version: Chrome latest
- OS and version: windows 11

### Describe the Bug

 Uncaught 
TypeError: Cannot read properties of null (reading 'useRef')
    at react_production_min.useRef (index-BJZNeC1P.js:40:217)
    at withSelector_production_min.useSyncExternalStoreWithSelector (__federation_expose_…-3-C9dJJ1.js:116:89)
    at useStoreWithEqualityFn (__federation_expose_…-3-C9dJJ1.js:173:17)
    at useStore (__federation_expose_…3-C9dJJ1.js:3745:10)
    at AriaLiveMessage (__federation_expose_…3-C9dJJ1.js:4880:27)
    at renderWithHooks (chunk-LLOTBQCN.js?v=be057b65:11566:26)
    at mountIndeterminateComponent (chunk-LLOTBQCN.js?v=be057b65:14944:21)
    at beginWork (chunk-LLOTBQCN.js?v=be057b65:15932:22)
    at HTMLUnknownElement.callCallback2 (chunk-LLOTBQCN.js?v=be057b65:3672:22)
    at Object.invokeGuardedCallbackDev (chunk-LLOTBQCN.js?v=be057b65:3697:24)
chunk-LLOTBQCN.js?v=be057b65:14050 The above error occurred in the <GraphView> component:
    at GraphView (http://localhost:3005/assets/__federation_expose_App-3-C9dJJ1.js:7139:22)
    at Wrapper (http://localhost:3005/assets/__federation_expose_App-3-C9dJJ1.js:7439:20)
    at div
    at http://localhost:3005/assets/__federation_expose_App-3-C9dJJ1.js:7470:33
    at div
    at ReactFlowProvider (http://localhost:3005/assets/__federation_expose_App-3-C9dJJ1.js:7431:30)
    at div
    at BasicFlow (http://localhost:3005/assets/__federation_expose_App-3-C9dJJ1.js:7613:36)
    at App (http://localhost:3005/assets/__federation_expose_App-3-C9dJJ1.js:7644:45)
    at Suspense
    at App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

### Steps to reproduce the bug or issue

Create react project through vite with all latest versions of react, react-dom, react-router-dom
And then add reactflow plugin in it.
then try to run npm un dev it shows the error

### Expected behavior

Don't assign null to useRef or just check the null and then render it

**Comment by moklick** [comment]
Did you try to remove node_modules and run `npm install` again?

If the issue persists, please re-open this issue with a repo that reproduces the problem.

**Comment by robinrd77** [comment]
Hi This issue is still there, in Vite module federation its not working
