### ISSUE TITLE
Can't test ReactFlow in vitest

### ISSUE THREAD

**Issue by miko-ck** [xyflow/xyflow#4483]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: `"@xyflow/react": "^12.0.1", "react": "^18.3.1",`
- Browser and version: Safari/605.1.15
- OS and version: MacOS 14.5 (23F79)

### Describe the Bug

I couldn't get the TS codesandbox to work, so I'll just post the code here. I'm trying to run this simple test vith `"vitest": "^2.0.4"`:

```typescript
import "@testing-library/jest-dom";
import { render } from "@testing-library/react";
import { ReactFlow } from "@xyflow/react";
import "react";
import { describe, test } from "vitest";
import { mockReactFlow } from "../../designer/testing/mockReactFlow"; // this is the thing you recommended on your testing doc page

describe("mini test", () => {
    beforeEach(() => {
        mockReactFlow();
    });

    test("should work", () => {
        const {container} = render(<ReactFlow />); // This is the simplest example I could come up with
    });
});
```

When I run it, I get the following error (repeated a few times, I'm pasting only once):

```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
Error: Uncaught [TypeError: Cannot read properties of null (reading 'useState')]
    at reportException (......../node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at innerInvokeEventListeners (......../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:353:9)
    at invokeEventListeners (......../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:286:3)
    at HTMLUnknownElementImpl._dispatch (......../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:9)
    at HTMLUnknownElementImpl.dispatchEvent (......../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:104:17)
    at HTMLUnknownElement.dispatchEvent (......../node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34)
    at Object.invokeGuardedCallbackDev (......../node_modules/react-dom/cjs/react-dom.development.js:4213:16)
    at invokeGuardedCallback (......../node_modules/react-dom/cjs/react-dom.development.js:4277:31)
    at beginWork$1 (......../node_modules/react-dom/cjs/react-dom.development.js:27451:7)
    at performUnitOfWork (......../node_modules/react-dom/cjs/react-dom.development.js:26560:12) TypeError: Cannot read properties of null (reading 'useState')
    at useState (......../node_modules/react/cjs/react.development.js:1622:21)
    at useColorModeClass (......../node_modules/@xyflow/react/dist/esm/index.mjs:279:49)
    at ReactFlow (......../node_modules/@xyflow/react/dist/esm/index.mjs:2935:32)
    at renderWithHooks (......../node_modules/react-dom/cjs/react-dom.development.js:16305:18)
    at updateForwardRef (......../node_modules/react-dom/cjs/react-dom.development.js:19226:20)
    at beginWork (......../node_modules/react-dom/cjs/react-dom.development.js:21636:16)
    at HTMLUnknownElement.callCallback (......../node_modules/react-dom/cjs/react-dom.development.js:4164:14)
    at HTMLUnknownElement.callTheUserObjectsOperation (......../node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
    at innerInvokeEventListeners (......../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:350:25)
    at invokeEventListeners (......../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:286:3)
The above error occurred in the <ForwardRef(ReactFlow)> component:

    at ReactFlow (......../node_modules/@xyflow/react/dist/esm/index.mjs:2933:22)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```

### Steps to reproduce the bug or issue

1. create a new React project using vite
2. install @xyflow/react, vitest, possibly some other dependencies
3. create the test file
4. run vitest

### Expected behavior

I expected this test to pass.

### Additional context

I'm a pro customer.

**Comment by moklick** [comment]
Thanks for the report. We will check it!

**Comment by miko-ck** [comment]
Hey, it took me some time but I eventually figured out that's a problem with my project configuration: I suspect I had 2 versions of React included at some point. This was my smallest possible example of a failing test:

```typescript
       const Z: React.FC<{}> = ({}) => {
           useEffect(() => { console.log("Test"); }, []); // it worked without this line
           return <div>Test</div>;
       };
       render(<Z />);
```
 
In any case, I could get RF working in vitest, so this can probably be closed.
